### ISSUE TITLE
New Plugin within NewRelic

### ISSUE THREAD

**Issue by Rockstar04** [NewRelic-Python-Plugins/newrelic-python-agent#15]
Currently when you use our fork, your metrics are still displayed in NewRelic as the Poison Pen, LLC (MeetMe) plugin. This means that users still get sent to their repo for support and we don't have control over the dashboards in New Relic.

Since we don't have currently support anything different I don't think this is a major issue, and possibly one we can wait for until we start writing our new plugins.

**Comment by tjstansell** [comment]
While the new mysql plugin is also pointed to the official newrelic mysql GUID to get access to their dashboard, it too says the version is old and points them at the java plugin.  I believe that #16 is also a dashboard bug, so the only way to fix it would be to actually make our own GUID space and manage our own dashboards.  I'm not exactly sure the best way to do this to allow us to collaborate on the dashboards, though.  Since we're all from different companies, I'm not sure how we create a newrelic entity/login that we all would be able to log in as to collaborate on the plugin.

**Comment by wolph** [comment]
Can't we simply create a new organisation and use a separate login for that? Not entirely sure if that would work but it's probably more viable.

**Comment by tjstansell** [comment]
Maybe it's that simple.  I actually assumed newrelic was a paid-only thing ... but never really verified my assumption.  If we can just create a new organization, that works.

**Comment by wolph** [comment]
newrelic is freemium, the free version is rather limited but it's there
